LibraryBookRegistration/Book.cs

Created Book class that has:
- Constructor
- Properties: ISBN, Title, Price
- Method: ToString() 
Closes #1

Created Book class

---

LibraryBookRegistration/Customer.cs

Created customer class

---

LibraryBookRegistration/DBHelper.cs
LibraryBookRegistration/LibraryBookRegistration.csproj

I created DBHelper class with:
Please give me come comments!
Thank you very much!
Closes #5

Created DBHelper class with methods that returns SqlConnection

---

LibraryBookRegistration/BookDB.cs

I have created BookDB class with basic CRUD functionality:
We might need some advanced methods at a later stage:
- GetAllValidBooks();
- GetBooksExcludingISBN(isbn);
- GetBooksNotYetRegisterByCustomerID(customerID)
Please give me some feedbacks. Thank you!
Closes #7

Created BookDB class with basic CRUD Functionality for Book

---

LibraryBookRegistration/Validation.cs

Created Validation class with basic validation methods

---

LibraryBookRegistration/Validation.cs

Deleted RemoveAllWhiteSpace from Validation class

---

LibraryBookRegistration/DataConfiguration.cs

Campbell #22 create data configuration class

---

LibraryBookRegistration/FrmLibraryBookRegistration.Designer.cs
LibraryBookRegistration/FrmLibraryBookRegistration.cs

Some code added to make the label of Title blinking
Closes #4

Re-Created Main Form

---

LibraryBookRegistration/FrmManageRegistrations.Designer.cs
LibraryBookRegistration/FrmManageRegistrations.cs
LibraryBookRegistration/FrmManageRegistrations.resx

Created Registration Managing Form

---

LibraryBookRegistration/CustomerDB.cs

Campbell #6 create customer db class

---

LibraryBookRegistration/FrmManageCustomers.Designer.cs
LibraryBookRegistration/FrmManageCustomers.cs
LibraryBookRegistration/FrmManageCustomers.resx

(Tung Kim) Created customer managing form

---

LibraryBookRegistration/FrmLibraryBookRegistration.cs

(Tung Kim) Created a method to populate Customer ComboBox

---

LibraryBookRegistration/FrmLibraryBookRegistration.Designer.cs
LibraryBookRegistration/FrmLibraryBookRegistration.cs

Created method to open ManageReg form

---

LibraryBookRegistration/FrmManageCustomers.Designer.cs
LibraryBookRegistration/FrmManageCustomers.cs

Campbell issue#45 populate list view with customer data

---

LibraryBookRegistration/FrmLibraryBookRegistration.Designer.cs
LibraryBookRegistration/FrmLibraryBookRegistration.cs

Added functionality for Manage Customer button to open manage customer form

---

LibraryBookRegistration/FrmLibraryBookRegistration.Designer.cs
LibraryBookRegistration/FrmLibraryBookRegistration.cs

Campbell issue#50 create onload method for frm library book registration

---

LibraryBookRegistration/FrmManageCustomers.cs

Campbell issue#53 fix populate customer list view method

---

LibraryBookRegistration/FrmLibraryBookRegistration.Designer.cs
LibraryBookRegistration/FrmLibraryBookRegistration.cs

Added functionality to manage book button to open form of the same name

---

LibraryBookRegistration/FrmManageBook.Designer.cs
LibraryBookRegistration/FrmManageBook.cs

Campbell issue#46 populate list view

---

LibraryBookRegistration/DataConfiguration.cs

combined RemoveWhiteSpace() and RemoveAllWhiteSpace()

---

LibraryBookRegistration/DataConfiguration.cs

added a method to formalize Name/Book Title

---

LibraryBookRegistration.sql

Upload LibraryBookRegistration.sql

Add database file via upload

---

LibraryBookRegistration/Validation.cs

Added a method to check an isbn existed

---

LibraryBookRegistration/Validation.cs

added remove white space and dashes before validating isbn

---

LibraryBookRegistration/BookDB.cs

Added a BookDB method to get all books not yet registered by CustomerID

---

LibraryBookRegistration/BookDB.cs

Added GetAllValidBooks() method

---

LibraryBookRegistration/RegistrationDB.cs

Closes #76 
Added GetRegistrationsByCustomerID to enable completion of Issue #47

Added GetRegistrationsByCustomerID method

---

LibraryBookRegistration/CustomerDB.cs

Added a method to get all Customers who have registration(s) to CustomerDB class
Closes #80

Added a method to get all Customers who have registration(s)

---

LibraryBookRegistration/FrmLibraryBookRegistration.Designer.cs
LibraryBookRegistration/FrmLibraryBookRegistration.cs

Tungkim issue#83 main form book combobox add more features and refactor old code

---

LibraryBookRegistration/FrmManageRegistrations.Designer.cs
LibraryBookRegistration/FrmManageRegistrations.cs

Tungkim issue#47 registration manager form populate the listviews

---

LibraryBookRegistration/RegistrationDB.cs

Added method CountRegistrationsGroupByCustomerID

---

LibraryBookRegistration/FrmManageCustomers.Designer.cs
LibraryBookRegistration/FrmManageCustomers.cs

Tungkim issue#72 customer manager form all functionalities work

---

LibraryBookRegistration/FrmLibraryBookRegistration.cs

Main Form - Register button works

---

LibraryBookRegistration/FrmManageBook.Designer.cs
LibraryBookRegistration/FrmManageBook.cs
LibraryBookRegistration/RegistrationDB.cs

Closes #70 
All functions now work.
For Delete to work I had to add a new method to RegistrationDB. 
Let me know if that is ok or if you want it to be a separate Issue.

Campbell issue#70 functionality for manage book

---

LibraryBookRegistration/FrmManageCustomers.Designer.cs
LibraryBookRegistration/FrmManageCustomers.cs

Buttons on and off working properly!
Closes #67

Customer Managing Form - Buttons on and off working

---

LibraryBookRegistration/FrmManageBook.Designer.cs
LibraryBookRegistration/FrmManageBook.cs

Closes #69 
Created method to enable or disable the add book button.

Campbell issue#69 enable disable buttons

---

LibraryBookRegistration/FrmManageRegistrations.Designer.cs
LibraryBookRegistration/FrmManageRegistrations.cs

Campbell issue#68 create enable disable button reg form

---

LibraryBookRegistration/FrmLibraryBookRegistration.Designer.cs
LibraryBookRegistration/FrmLibraryBookRegistration.cs

Rework main form register button

---

LibraryBookRegistration/FrmManageBook.cs

Campbell issue#105 bug fix manage books

---

LibraryBookRegistration/FrmManageRegistrations.Designer.cs
LibraryBookRegistration/FrmManageRegistrations.cs

Registration Managing Form - Both Remove buttons work!
